### ISSUE TITLE
Checklist of things to do when deploying to prod

### ISSUE THREAD

**Issue by JustinMi** [BerkeleyAutomation/malasakit-v1#71]
- [ ] make sure `DEBUG=False`
- [x]  push to opinions.berkeley.edu/pcari-test
- [x] MySQL 
- [ ] create environment variables for `SECRET_KEY` 
- [x] and `mysql_pass`
- [x] create `superuser` account for admin panel
- [x] make sure all empty messages in `pcari_message` table in the MySQL database is set to `NULL`--see #46 
- [x] serve static files correctly--https://docs.djangoproject.com/en/1.10/howto/static-files/
- [ ] find a new place to store `collectstatic` files
- [ ] Git hook 
- [ ] [TODO] multiple settings files
- [ ] Set up prod server so you can never push on prod branch

**Comment by jonathan-j-lee** [comment]
Need to enable minification.

**Comment by jonathan-j-lee** [comment]
Replacing this with the [deployment milestone](https://github.com/BerkeleyAutomation/malasakit-v1/milestone/3).

**Comment by jonathan-j-lee** [comment]
Closing this, as [this procedure is now documented](https://github.com/BerkeleyAutomation/malasakit-v1/wiki/Deploying-to-Production).
